//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeechSynthesizerService.Service.Worker
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTSMessage
    {
        public System.Guid TTSMessageId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public int VoiceGenderId { get; set; }
        public string Message { get; set; }
        public string Filename { get; set; }
    
        public virtual VoiceGender VoiceGender { get; set; }
    }
}
